[package]
name = "upstream-releases-tracker-lib"
version = "3.2.2"
description = "Track releases from upstream repositories of projects"
authors = ["Mukund Yedunuthala <mukundkash1997@gmx.net>"]
edition = "2024"
license = "AGPL-3.0-or-later"
repository = "https://gitlab.com/mukund-yedunuthala/upstream-release-tracker-rs"
homepage = "https://gitlab.com/mukund-yedunuthala/upstream-release-tracker-rs"


[lib]
name = "upstream_releases_tracker_v2_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "^2", features = [] }

[dependencies]
tauri = { version = "^2", features = [] }
tauri-plugin-opener = "^2"
serde = { version = "^1.0.219", features = ["derive"] }
serde_json = "^1.0.140"
dirs = "^6.0.0"
reqwest = { version = "^0.13.2", features = ["blocking", "json"] }
regex = "^1.11.1"
tracker_libs = { path = "../tracker_libs" }
