[package]
name = "upstream-releases-tracker"
version = "3.0.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
web-sys = { version = "^0.3", features = ["Window"] }
js-sys = "^0.3"
serde = { version = "^1", features = ["derive"] }
console_error_panic_hook = "^0.1.7"
toml = "=0.8.23"
tracker_libs = { path = "./tracker_libs" }

[workspace]
members = ["src-tauri", "tracker_libs"]
